INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (1, 'Quem e o autor do Manifesto Comunista?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (2, 'Como e chamada a doenca que clareou a pele de Michael Jackson?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (3, 'Quem e o parceiro de aventuras de Dom Quixote?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (4, 'Violoncelo e um instrumento de?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (5, 'Em que estado brasileiro nasceu a apresentadora Xuxa?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (6, 'Qual era o apelido da cantora Elis Regina?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (7, 'Que imperador colocou fogo em Roma?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (8, 'A cidade de Pompeia, que foi soterrada por um vulcao fica em qual desses paises?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (9, 'Em que estadio Pele marcou seu milesimo gol?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (10, 'O que e um oboe?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (11, 'Quem realizou a primeira cirurgia de ponte de safena no brasil?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (12, 'Quem disse a frase: "Vim, vi e venci"?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (13, 'Beirute e a capital de que pais?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (14, 'Qual e a capital do Iraque?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (15, 'Qual presidente dos EUA foi ator de cinema?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (16, 'Em que cidade brasileira fica o ITA?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (17, 'O nome America foi associoado a qual desses nomes?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (18, 'Em que ano ocorreu o incendio do edificio Joelma, na cidade de Sao Paulo?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (19, 'Onde nasceu Van Gogh?');
INSERT INTO tb_pergunta(id_pergunta, titulo_pergunta) VALUES (20, 'Qual oceano tem o maior volume de agua?');
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (1, 'Lenin', 1, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (2, 'Gorbatchov', 1, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (3, 'Karl Marx', 1, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (4, 'Allan Kardec', 1, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (5, 'Vitiligo', 2, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (6, 'Astigmatismo', 2, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (7, 'Pedofilia', 2, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (8, 'Bruxismo', 2, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (9, 'Guilherme Tell', 3, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (10, 'Sancho Panca', 3, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (11, 'Sigmund Freud', 3, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (12, 'Lancelot', 3, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (13, 'Percussao', 4, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (14, 'Sopro', 4, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (15, 'Repercussao', 4, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (16, 'Cordas', 4, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (17, 'Rio de Janeiro', 5, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (18, 'Parana', 5, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (19, 'Santa Catarina', 5, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (20, 'Rio Grande do Sul', 5, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (21, 'Gauchinha', 6, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (22, 'Paulistinha', 6, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (23, 'Pimentinha', 6, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (24, 'Andorinha', 6, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (25, 'Nero', 7, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (26, 'Adriano', 7, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (27, 'Julio Cesar', 7, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (28, 'Brutus', 7, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (29, 'Japao', 8, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (30, 'Italia', 8, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (31, 'Chile', 8, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (32, 'Mexico', 8, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (33, 'Morumbi', 9, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (34, 'Pacaembu', 9, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (35, 'Maracana', 9, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (36, 'Mineirao', 9, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (37, 'Vulcao', 10, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (38, 'Comida', 10, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (39, 'Instrumento musical', 10, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (40, 'Tribo indigena', 10, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (41, 'DR. Zerbini', 11, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (42, 'DR. Fritz', 11, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (43, 'DR. Jatene', 11, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (44, 'DR. Calligari', 11, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (45, 'Julio Cesar', 12, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (46, 'Calagola', 12, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (47, 'Nero', 12, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (48, 'Marco Antonio', 12, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (49, 'Siria', 13, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (50, 'Nepal', 13, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (51, 'Mongolia', 13, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (52, 'Libano', 13, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (53, 'Belem', 14, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (54, 'Bagda?', 14, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (55, 'Beirute', 14, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (56, 'Budapeste', 14, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (57, 'Ronald Reagan', 15, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (58, 'George Bush', 15, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (59, 'Richard Nixon', 15, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (60, 'Bill Clinton', 15, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (61, 'Sao Jose do Rio Preto', 16, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (62, 'Sao Jose dos Pinhais', 16, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (63, 'Sao Jose dos Campos', 16, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (64, 'Sao Jose dos Santos', 16, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (65, 'Americo dos Reis', 17, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (66, 'Americo Vespucio', 17, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (67, 'Americo Brasiliense', 17, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (68, 'Jose Americo da Silva', 17, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (69, '1971', 18, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (70, '1972', 18, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (71, '1973', 18, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (72, '1974', 18, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (73, 'Polonia', 19, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (74, 'Franca', 19, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (75, 'Holanda', 19, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (76, 'Italia', 19, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (77, 'Atlantico', 20, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (78, 'Pacifico', 20, 1);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (79, 'Morto', 20, 0);
INSERT INTO tb_resposta(id_resposta, titulo_resposta, id_pergunta, isvalido) VALUES (80, 'Indico', 20, 0);