
package br.com.netquiz.cliente.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JogoImplService", targetNamespace = "http://webservice.servidor.netquiz.com.br/", wsdlLocation = "http://localhost:7070/NetQuiz/Jogo?wsdl")
public class JogoImplService
    extends Service
{

    private final static URL JOGOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException JOGOIMPLSERVICE_EXCEPTION;
    private final static QName JOGOIMPLSERVICE_QNAME = new QName("http://webservice.servidor.netquiz.com.br/", "JogoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:7070/NetQuiz/Jogo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JOGOIMPLSERVICE_WSDL_LOCATION = url;
        JOGOIMPLSERVICE_EXCEPTION = e;
    }

    public JogoImplService() {
        super(__getWsdlLocation(), JOGOIMPLSERVICE_QNAME);
    }

    public JogoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JOGOIMPLSERVICE_QNAME, features);
    }

    public JogoImplService(URL wsdlLocation) {
        super(wsdlLocation, JOGOIMPLSERVICE_QNAME);
    }

    public JogoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JOGOIMPLSERVICE_QNAME, features);
    }

    public JogoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JogoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Jogo
     */
    @WebEndpoint(name = "JogoImplPort")
    public Jogo getJogoImplPort() {
        return super.getPort(new QName("http://webservice.servidor.netquiz.com.br/", "JogoImplPort"), Jogo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Jogo
     */
    @WebEndpoint(name = "JogoImplPort")
    public Jogo getJogoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.servidor.netquiz.com.br/", "JogoImplPort"), Jogo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JOGOIMPLSERVICE_EXCEPTION!= null) {
            throw JOGOIMPLSERVICE_EXCEPTION;
        }
        return JOGOIMPLSERVICE_WSDL_LOCATION;
    }

}
