
package br.com.netquiz.cliente.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Jogo", targetNamespace = "http://webservice.servidor.netquiz.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Jogo {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registrar", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.Registrar")
    @ResponseWrapper(localName = "registrarResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.RegistrarResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/registrarRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/registrarResponse")
    public void registrar(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountConectado", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetCountConectado")
    @ResponseWrapper(localName = "getCountConectadoResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetCountConectadoResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/getCountConectadoRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/getCountConectadoResponse")
    public int getCountConectado();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIdDaRodada", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetIdDaRodada")
    @ResponseWrapper(localName = "getIdDaRodadaResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetIdDaRodadaResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/getIdDaRodadaRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/getIdDaRodadaResponse")
    public String getIdDaRodada();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "setProximoJogador", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.SetProximoJogador")
    @ResponseWrapper(localName = "setProximoJogadorResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.SetProximoJogadorResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/setProximoJogadorRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/setProximoJogadorResponse")
    public void setProximoJogador();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMenuPerguntas", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetMenuPerguntas")
    @ResponseWrapper(localName = "getMenuPerguntasResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetMenuPerguntasResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/getMenuPerguntasRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/getMenuPerguntasResponse")
    public String getMenuPerguntas();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPergunta", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetPergunta")
    @ResponseWrapper(localName = "getPerguntaResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetPerguntaResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/getPerguntaRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/getPerguntaResponse")
    public String getPergunta(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAcertoPergunta", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.IsAcertoPergunta")
    @ResponseWrapper(localName = "isAcertoPerguntaResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.IsAcertoPerguntaResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/isAcertoPerguntaRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/isAcertoPerguntaResponse")
    public Boolean isAcertoPergunta(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRanking", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetRanking")
    @ResponseWrapper(localName = "getRankingResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.GetRankingResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/getRankingRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/getRankingResponse")
    public String getRanking();

    /**
     * 
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fimDoJogo", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.FimDoJogo")
    @ResponseWrapper(localName = "fimDoJogoResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.FimDoJogoResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/fimDoJogoRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/fimDoJogoResponse")
    public Boolean fimDoJogo();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isPerguntaValida", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.IsPerguntaValida")
    @ResponseWrapper(localName = "isPerguntaValidaResponse", targetNamespace = "http://webservice.servidor.netquiz.com.br/", className = "br.com.netquiz.cliente.ws.IsPerguntaValidaResponse")
    @Action(input = "http://webservice.servidor.netquiz.com.br/Jogo/isPerguntaValidaRequest", output = "http://webservice.servidor.netquiz.com.br/Jogo/isPerguntaValidaResponse")
    public Boolean isPerguntaValida(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
